apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-certificate
spec:
  secretName: bank-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: bank.micorfinance.site
  dnsNames:
    - bank.micorfinance.site
    - bankapi.micorfinance.site